// models/Artifact.js
// ============================================================
// ARTIFACT: Any file stored in the system (images, PDFs, etc.)
// Part of the ArtifactManager system
// ============================================================

import mongoose from "mongoose";

const ArtifactSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Grid this artifact belongs to
    gridId: { type: String, required: true, index: true },

    // Folder location in tree (null = root)
    folderId: { type: String, default: null, index: true },

    // File info
    name: { type: String, required: true },
    mimeType: { type: String, default: "application/octet-stream" },
    extension: { type: String, default: "" }, // e.g., "pdf", "png", "jpg"
    size: { type: Number, default: 0 }, // bytes

    // Storage location
    storageType: {
      type: String,
      enum: ["local", "mongodb", "s3", "url"],
      default: "mongodb",
    },
    storagePath: { type: String }, // path or URL depending on storageType
    storageId: { type: String }, // GridFS ObjectId if using mongodb

    // For images/thumbnails
    thumbnailPath: { type: String },
    dimensions: {
      width: { type: Number },
      height: { type: Number },
    },

    // Display settings
    icon: { type: String, default: null }, // override icon
    color: { type: String, default: null },

    // Order within folder
    sortOrder: { type: Number, default: 0 },

    // Artifact type for special handling
    artifactType: {
      type: String,
      enum: ["file", "image", "video", "audio", "pdf", "archive", "other"],
      default: "file",
    },

    // Soft delete
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date },

    // Optional metadata (exif, custom properties, etc.)
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes
ArtifactSchema.index({ gridId: 1, folderId: 1 });
ArtifactSchema.index({ gridId: 1, sortOrder: 1 });
ArtifactSchema.index({ gridId: 1, isDeleted: 1 });

// Hide Mongo internals
ArtifactSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Artifact", ArtifactSchema);
