// models/Doc.js
// ============================================================
// DOC: Rich text document with embedded pills
// Separate from panel types - docs are first-class entities
// Part of the ArtifactManager system (docs are a type of artifact)
// ============================================================

import mongoose from "mongoose";

// DocPill sub-schema for tracking embedded pills
const DocPillSchema = new mongoose.Schema(
  {
    // Pill type
    type: {
      type: String,
      enum: ["instance", "field", "expression", "link", "text"],
      required: true,
    },

    // Reference IDs based on type
    instanceId: { type: String }, // for instance pills
    occurrenceId: { type: String }, // specific occurrence reference
    fieldId: { type: String }, // for field pills

    // For text pills (words converted to pills)
    text: { type: String },

    // For expression pills (inline block trees)
    expression: { type: mongoose.Schema.Types.Mixed },

    // For link pills (doc links)
    targetDocId: { type: String },

    // Position in document (for reconstruction)
    position: { type: Number },

    // Link mode for instance/field pills
    linkMode: {
      type: String,
      enum: ["copy", "copylink"],
      default: "copy",
    },
  },
  { _id: false }
);

const DocSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Grid this doc belongs to
    gridId: { type: String, required: true, index: true },

    // Folder location in tree (null = root)
    folderId: { type: String, default: null, index: true },

    // Doc info
    title: { type: String, default: "Untitled" },
    icon: { type: String, default: "file-text" }, // icon name or emoji

    // Tiptap/ProseMirror JSON content
    content: { type: mongoose.Schema.Types.Mixed, default: null },

    // Extracted pills for quick lookup/aggregation
    pills: { type: [DocPillSchema], default: [] },

    // Order within folder
    sortOrder: { type: Number, default: 0 },

    // Doc type for special handling
    docType: {
      type: String,
      enum: ["normal", "day-page", "template", "journal"],
      default: "normal",
    },

    // For day-page docs: which date
    dayPageDate: { type: Date, index: true },

    // Template info (for template docs)
    templateId: { type: String }, // if created from template
    isTemplate: { type: Boolean, default: false },

    // Iteration context (for day pages and time-based filtering)
    iteration: {
      timeValue: { type: Date },
      timeFilter: { type: String, enum: ["daily", "weekly", "monthly", "yearly", "all"] },
      categoryKey: { type: String },
      categoryValue: { type: String },
    },

    // Soft delete
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes
DocSchema.index({ gridId: 1, folderId: 1 });
DocSchema.index({ gridId: 1, docType: 1 });
DocSchema.index({ gridId: 1, dayPageDate: 1 });
DocSchema.index({ gridId: 1, sortOrder: 1 });
DocSchema.index({ gridId: 1, isDeleted: 1 });

// Hide Mongo internals
DocSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Doc", DocSchema);
