// models/Field.js
import mongoose from "mongoose";

const FieldSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Field name
    name: { type: String, required: true, trim: true },

    // Field data type
    type: {
      type: String,
      required: true,
      enum: ["number", "text", "boolean", "select", "date"],
      default: "text"
    },

    // Optional unit (for number fields)
    unit: { type: String },

    // Field mode: input or calculated/derived
    mode: {
      type: String,
      required: true,
      enum: ["input", "derived"],
      default: "input"
    },

    // Calculation/metric definition (only used when mode = "derived")
    // This will be fully implemented in Phase 2
    metric: {
      source: { type: String, enum: ["transactions", "occurrences"] },
      fieldId: { type: String },  // Source field to aggregate
      instanceIds: { type: [String], default: [] },  // Optional filter by instance types
      aggregation: { type: String, enum: ["sum", "count", "countTrue", "avg", "min", "max", "last"] },
      scope: { type: String, enum: ["grid", "panel", "container", "custom"] },
      window: { type: String, enum: ["day", "week", "month", "year", "iteration", "all"] },
      target: {
        value: { type: mongoose.Schema.Types.Mixed },
        op: { type: String, enum: [">=", "<=", "==", "!=", ">", "<"] },
        // Base time filter for the target (e.g., "daily" means target is per day)
        // When viewing weekly, a daily target of 3 becomes 21
        timeFilter: { type: String, enum: ["daily", "weekly", "monthly", "yearly", "inherit"] }
      },
      // Source field time filter - "inherit" uses parent iteration
      timeFilter: { type: String, enum: ["daily", "weekly", "monthly", "yearly", "inherit", "all"] },
      // Allowed source fields with their flow filters and destinations
      allowedFields: [{
        fieldId: { type: String },
        flowFilter: { type: String, enum: ["any", "in", "out"], default: "any" },
        destinations: [{ type: mongoose.Schema.Types.Mixed }]
      }]
    },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Indexes for queries
FieldSchema.index({ userId: 1, name: 1 });
FieldSchema.index({ mode: 1 });

// Hide Mongo internals in API responses
FieldSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Field", FieldSchema);
