// models/Occurrence.js
import mongoose from "mongoose";

const OccurrenceSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // What this occurrence represents
    targetType: {
      type: String,
      required: true,
      enum: ["panel", "container", "instance", "doc"],
      index: true
    },
    targetId: { type: String, required: true, index: true },

    // Grid this occurrence belongs to
    gridId: { type: String, required: true, index: true },

    // Iteration context (for filtering/time-travel later)
    // Supports COMPOUND iterations: time-based + category-based simultaneously
    iteration: {
      // Legacy single-key format (backwards compatible)
      key: { type: String, default: "time" },  // "time" | "version" | "category" | custom
      value: { type: mongoose.Schema.Types.Mixed },  // Date, string, number, etc - null means "all iterations"
      range: { type: mongoose.Schema.Types.Mixed },  // Optional for ranges

      // TIME-BASED iteration (when in time, e.g., daily/weekly/monthly)
      timeValue: { type: Date },  // The specific date
      timeFilter: { type: String, enum: ["daily", "weekly", "monthly", "yearly", "all"] },

      // CATEGORY-BASED iteration (what category, e.g., "work", "personal")
      categoryKey: { type: String },   // e.g., "project", "context", "tag"
      categoryValue: { type: String }, // e.g., "work", "personal", "health"

      // Inheritance mode: does this entity use parent's iteration or its own?
      // "inherit" - Use parent's iteration context (grid → panel → container → instance)
      // "own" - Use this entity's own iteration settings (enables local navigation arrows)
      inheritMode: { type: String, enum: ["inherit", "own"], default: "inherit" },

      // Persistence mode: how this occurrence behaves across iterations
      // "persistent" - Shows on ALL iterations (templates, habits in toolkit)
      // "specific" - Only shows on the specific iteration.value date
      // "untilDone" - Shows on all iterations until completed, then becomes specific
      mode: { type: String, enum: ["persistent", "specific", "untilDone"], default: "specific" },

      // When mode="untilDone" and item is completed, this records when
      completedOn: { type: Date },

      // For "untilDone" mode: which field to check for completion
      completionFieldId: { type: String },
    },

    // Timestamp for this occurrence
    timestamp: { type: Date, default: Date.now, index: true },

    // Panel placement (only used when targetType = "panel")
    placement: {
      row: { type: Number },
      col: { type: Number },
      width: { type: Number },
      height: { type: Number }
    },

    // Optional snapshot of field values (for UI convenience)
    // Actual field values can also be computed from transactions in Phase 3
    fields: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Doc content (for doc container occurrences)
    // Stores Tiptap/ProseMirror JSON document structure
    // Each occurrence can have its own content (e.g., different day pages)
    docContent: { type: mongoose.Schema.Types.Mixed, default: null },

    // Copylink: linked occurrence ID — when set, field edits propagate to all
    // occurrences sharing the same linkedGroupId
    linkedGroupId: { type: String, default: null, index: true },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes for common queries
OccurrenceSchema.index({ gridId: 1, targetType: 1 });
OccurrenceSchema.index({ gridId: 1, timestamp: -1 });
OccurrenceSchema.index({ targetId: 1, gridId: 1 });
OccurrenceSchema.index({ "iteration.key": 1, "iteration.value": 1 });

// Hide Mongo internals in API responses
OccurrenceSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Occurrence", OccurrenceSchema);
