// models/Occurrence.js
import mongoose from "mongoose";

const OccurrenceSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // What this occurrence represents
    targetType: {
      type: String,
      required: true,
      enum: ["panel", "container", "instance"],
      index: true
    },
    targetId: { type: String, required: true, index: true },

    // Grid this occurrence belongs to
    gridId: { type: String, required: true, index: true },

    // Iteration context (for filtering/time-travel later)
    iteration: {
      key: { type: String, default: "time" },  // "time" | "version" | "category" | custom
      value: { type: mongoose.Schema.Types.Mixed },  // Date, string, number, etc
      range: { type: mongoose.Schema.Types.Mixed }   // Optional for ranges
    },

    // Timestamp for this occurrence
    timestamp: { type: Date, default: Date.now, index: true },

    // Panel placement (only used when targetType = "panel")
    placement: {
      row: { type: Number },
      col: { type: Number },
      width: { type: Number },
      height: { type: Number }
    },

    // Optional snapshot of field values (for UI convenience)
    // Actual field values can also be computed from transactions in Phase 3
    fields: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes for common queries
OccurrenceSchema.index({ gridId: 1, targetType: 1 });
OccurrenceSchema.index({ gridId: 1, timestamp: -1 });
OccurrenceSchema.index({ targetId: 1, gridId: 1 });
OccurrenceSchema.index({ "iteration.key": 1, "iteration.value": 1 });

// Hide Mongo internals in API responses
OccurrenceSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Occurrence", OccurrenceSchema);
