import mongoose from "mongoose";

const PanelSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },          // UUID generated by client
    gridId: { type: String},      // <-- REQUIRED for multi-grid
    type: { type: String, default: "" },
    row: { type: Number, default: 0 },
    col: { type: Number, default: 0 },
    width: { type: Number, default: 1 },
    height: { type: Number, default: 1 },
    userId: { type: String, required: true },
    containers: { type: [String], default: [] },
  },
  { timestamps: true }
);

export default mongoose.model("Panel", PanelSchema);
