import mongoose from "mongoose";

const PanelSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },       // UUID generated by client
    gridId: { type: String },                   // multi-grid
    type: { type: String, default: "" },
    name: { type: String },

    userId: { type: String, required: true },

    // Occurrences in this panel (array of occurrence IDs)
    occurrences: { type: [String], default: [] },
    kind: { type: String, enum: ["board", "doc", "mixed"], default: "board" },

    // Iteration settings (inherit from grid or own)
    iteration: {
      mode: { type: String, enum: ["inherit", "own"], default: "inherit" },
      timeFilter: { type: String, enum: ["daily", "weekly", "monthly", "yearly"], default: "daily" },
    },

    // Default drag mode for this panel
    defaultDragMode: { type: String, enum: ["move", "copy"], default: "move" },

    // Fields exposed in this panel
    fieldIds: { type: [String], default: [] },

    // ✅ keep if you still use it
    styles: { type: [mongoose.Schema.Types.Mixed], default: [] },

    // ✅ NEW: persisted list layout settings
    layout: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: true }
);

export default mongoose.model("Panel", PanelSchema);
